baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'DOVER POTTERY STUDIO'



pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[Params]
subtitle = "building a pottery community"
mainSections = ["posts"]
logo = "img/dps-logo-v2-gold.png"
hideAuthor = true
tags = false

#[[menus.main]]
#name = 'Home'
#pageRef = '/'
#weight = 10

#[[menus.main]]
#name = 'News'
#pageRef = '/posts'
#weight = 20

#[[menus.main]]
#name = 'Tags'
#pageRef = '/tags'
#weight = 30

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
