baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'DOVER POTTERY STUDIO'
theme = ["hugo-easy-gallery"]

pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[Params]
subtitle = "a community artspace"
mainSections = ["posts"]
logo = "img/dps-logo-v2-gold.png"
hideAuthor = true
tags = false

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Classes'
url = 'https://doverpotterystudio.kilnfire.com/classes'
weight = 20

[[menus.main]]
name = 'Supplies'
url = 'https://doverpotterystudio.kilnfire.com/supplies'
weight = 30

[[menus.main]]
  name = "Facebook"
  url = "https://facebook.com/doverpottery.studio"
  weight = 30

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
